[package]
name = "satan/td-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Reflex = "littensy/reflex@4.3.1"
ReactReflex = "littensy/react-reflex@0.3.5"
TestEZ = "roblox/testez@0.4.1"
React = "jsdotlua/react@17.1.0"
Sift = "csqrl/sift@0.0.8"
Knit = "sleitnick/knit@1.7.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
Promise = "evaera/promise@4.0.0"
Signal = "data-oriented-house/lemonsignal@1.10.0"

[server-dependencies]
datakeep = "noahrepublic/datakeep@3.1.1"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
server-packages = "game.ServerStorage.ServerPackages"